### ISSUE TITLE
fix pop bug

### ISSUE THREAD

**Issue by lloydbenson** [fishin/bait#10]
/Users/lbenson/scm/fishin/gills/node_modules/tacklebox/node_modules/bait/lib/index.js:393
        internals.activeRuns[jobId].pids.pop();
                                   ^
TypeError: Cannot read property 'pids' of undefined
    at ChildProcess.<anonymous> (/Users/lbenson/scm/fishin/gills/node_modules/tacklebox/node_modules/bait/lib/index.js:393:36)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)

**Comment by lloydbenson** [comment]
haven't run into this since rearchitecture.  Closing.
